### ISSUE TITLE
simpleframework don't include the license file 

### ISSUE THREAD

**Issue by puntogil** [ngallagher/simpleframework#7]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by ngallagher** [comment]
Its Apache BSD every source file has the licence in the header.

**Comment by puntogil** [comment]
This not solve the problem
again thanks

**Comment by ngallagher** [comment]
What problem, there is none. Add the LICENSE file yourself if u like??
--------------------------------------------
On Tue, 26/5/15, puntogil <notifications@github.com> wrote:

 Subject: Re: [simpleframework] simpleframework don't include the license file  (#7)
 To: "ngallagher/simpleframework" <simpleframework@noreply.github.com>
 Cc: "ngallagher" <gallagher_niall@yahoo.com>
 Received: Tuesday, 26 May, 2015, 1:43 AM
 
 This not solve the problem
 
 again thanks
 
 —
 Reply to this email directly or view
 it on GitHub.
