### ISSUE TITLE
Unable to migrate to 6.0.1

### ISSUE THREAD

**Issue by galan** [ngallagher/simpleframework#8]
Hi, I'm using version 5.1.6, but I don't know how to migrate to version 6.0.1.

I'm using maven and I'm not sure which dependencies are required now, see http://mvnrepository.com/artifact/org.simpleframework (I tried simple-http and simple-transport)

Beside of this, I can not find the the Server class I use currently, what class do I have to use instead.

Also please update the document: http://www.simpleframework.org/doc/tutorial/tutorial.php

Thank you

**Comment by ngallagher** [comment]
Server is now called SocketProcessor and the previous Processor is now called TransportProcessor, pretty much everything else is the same.
--------------------------------------------
On Wed, 25/2/15, Daniel Galán y Martins <notifications@github.com> wrote:

 Subject: [simpleframework] Unable to migrate to 6.0.1 (#8)
 To: "ngallagher/simpleframework" <simpleframework@noreply.github.com>
 Received: Wednesday, 25 February, 2015, 4:49 AM
 
 Hi, I'm using version 5.1.6,
 but I don't know how to migrate to version 6.0.1.
 
 I'm using maven and I'm not sure which
 dependencies are required now, see http://mvnrepository.com/artifact/org.simpleframework
 (I tried simple-http and simple-transport)
 
 Beside of this, I can not find the the Server class I use
 currently, what class do I have to use instead.
 
 Also please update the document: http://www.simpleframework.org/doc/tutorial/tutorial.php
 
 Thank you
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by galan** [comment]
Thank you, beside of this, the `ContainerServer` also renamed to `ContainerSocketProcessor`. As mentioned earlier, you should really update the documentation, otherwise new users won't be able to see it the simpleframework working.
