### ISSUE TITLE
ThreadFactory for DaemonFactory

### ISSUE THREAD

**Issue by mschonaker** [ngallagher/simpleframework#9]
Hi, Niall.

I'm experiencing some issues with the threads created by `org.simpleframework.common.thread.DaemonFactory.createThread(Runnable)`. I am struggling with Java security permissions, threads groups and related stuff. I have patched (hardcoded) the class so it creates threads according to my needs (assign a group and create the threads in certain `AccessControlContext`, priority, etc). In particular, the problem are those threads created for processing streams on demand and that are then recycled to listen to requests.

I think that in an ideal scenario it would be nice to be able to parameterize that class with an optional `java.util.concurrent.ThreadFactory`, having a default `ThreadFactory` for the current behaviour. 

What do you think? Would you be interested in a pull request?

**Comment by ngallagher** [comment]
Attach some code and ill add it in when I get the chance.

--------------------------------------------
On Wed, 4/3/15, Martín Schonaker <notifications@github.com> wrote:

 Subject: [simpleframework] ThreadFactory for DaemonFactory (#9)
 To: "ngallagher/simpleframework" <simpleframework@noreply.github.com>
 Received: Wednesday, 4 March, 2015, 2:17 AM
 
 Hi, Niall.
 
 I'm experiencing some issues with the threads created
 by
 org.simpleframework.common.thread.DaemonFactory.createThread(Runnable).
 I am struggling with Java security permissions, threads
 groups and related stuff. I have patched (hardcoded) the
 class so it creates threads according to my needs (assign a
 group and create the threads in certain
 AccessControlContext, priority, etc). In
 particular, the problem are those threads created for
 processing streams on demand and that are then recycled to
 listen to requests.
 
 I think that in an ideal scenario it would be nice to be
 able to parameterize that class with an optional
 java.util.concurrent.ThreadFactory, having a
 default ThreadFactory for the current
 behaviour. 
 
 What do you think? Would you be interested in a pull
 request?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by mschonaker** [comment]
Pull request on #10.
